project_id = "lkghvrwekhtfegrwmoft"

[functions.analyze-links]
verify_jwt = false

[functions.generate-script]
verify_jwt = false

[functions.generate-voice]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.generate-avatar-video]
verify_jwt = false