// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkghvrwekhtfegrwmoft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrZ2h2cndla2h0ZmVncndtb2Z0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNDk0MjksImV4cCI6MjA3MzYyNTQyOX0.vtXOJWf9uJID-a1IE_1S4ACQ8oBlXvECLf_UeDnnJw4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});